### PR TITLE
update devise signup

### PR DESCRIPTION
**Pull request by Georgy5**
What I did
Added the fields for dog name and owner_name.
Added bootstrap container and row.

How to test
http://localhost:3000/users/sign_up

### CODE REVIEW

**Comment by huyserp** [comment]
its seems bootstrap isn't having an affect on the forms...?

**Comment by Georgy5** [comment]
I thought the issue might just be local to me   ....I'll have to figure out why it looks messed up 
image
I'd spent a lot of time looking at it with Vlad, but haven't figured it out yet.

This is what it looked like before my changes:
image

**Comment by Georgy5** [comment]
## Fixed
I had to run ` rails generate simple_form:install --bootstrap`
Styling both the devise forms will be a seperate PR

grafik

**Comment by LG-2** [comment]
Looks much better now :)

**Pull request merged**
