### PR TITLE
added the space

### PR DESCRIPTION
**Pull request by huyserp**
Margins all around, also changed the line-hight of the text to make it a bit more airy. 
Screen Shot 2021-03-10 at 11 49 07 PM

### CODE REVIEW

**Comment by markMounsey** [comment]
Recommend we add padding to the bottom (16px) of the address in .info-box p#adrs to provided equal spacing between the address, the border line and the content below it. See below for more information:

Current state:
Screen Shot 2021-03-11 at 10 55 06

Recommended state:
Screen Shot 2021-03-11 at 10 53 43

Recommended changes:
Screen Shot 2021-03-11 at 10 54 19

Let me know your thoughts prior to merging. Thanks!

**Comment by huyserp** [comment]
> Recommend we add padding to the bottom (16px) of the address in .info-box p#adrs to provided equal spacing between the address, the border line and the content below it. See below for more information:
> 
> Current state:
> Screen Shot 2021-03-11 at 10 55 06
> 
> Recommended state:
> Screen Shot 2021-03-11 at 10 53 43
> 
> Recommended changes:
> Screen Shot 2021-03-11 at 10 54 19
> 
> Let me know your thoughts prior to merging. Thanks!

**Comment by huyserp** [comment]
> Recommend we add padding to the bottom (16px) of the address in .info-box p#adrs to provided equal spacing between the address, the border line and the content below it. See below for more information:
> 
> Current state:
> Screen Shot 2021-03-11 at 10 55 06
> 
> Recommended state:
> Screen Shot 2021-03-11 at 10 53 43
> 
> Recommended changes:
> Screen Shot 2021-03-11 at 10 54 19
> 
> Let me know your thoughts prior to merging. Thanks!

That works for me! I was kind of shootin in the dark :D I'll add that and push it up again

**Comment by markMounsey** [comment]
My originally recommendation was to add padding-bottom, but instead of adding a 4th property we can simply adjust the padding property that's already there => padding: 4px 4px 16px;. Just a thought.

**Comment by markMounsey** [comment]
Looks good. Thanks. Merged.

**Pull request merged**
